[debian-bookworm]
target = 'debian-bookworm'
arch = 'amd64'
dir = 'debian-bookworm-amd64'
post_script = 'post-script.sh'

[fedora-28]
target = 'fedora-28'
arch = 'amd64'
dir = 'fedora-28-amd64'
post_script = 'post-script.sh'
